spring.application.name=webcrawler
spring.main.web-application-type=none
seed.host=https://books.toscrape.com/
seed.page=index.html
crawler.output=crawler-output
top.N=20
crawler.pagesToCrawl=2
crawler.writeToFile=false
